In [1]:
import numpy as np

In [10]:
box = [0,1,0,1]
nx = 5
ny = 3
NN = (nx+1)*(ny+1)
NC = nx*ny

In [12]:
node = np.zeros((NN,2))
X1,Y1= np.mgrid[:box[1]:complex(nx+1),:box[3]:complex(ny+1)]#return mesh-grid ndarrays all of the same dimensions
X=X1.T
Y=Y1.T
print(X)
print(Y)

[[0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]]
[[0.         0.         0.         0.         0.         0.        ]
 [0.33333333 0.33333333 0.33333333 0.33333333 0.33333333 0.33333333]
 [0.66666667 0.66666667 0.66666667 0.66666667 0.66666667 0.66666667]
 [1.         1.         1.         1.         1.         1.        ]]


In [13]:
node[:,0] = X.flatten()#按行取出矩阵X中的元素
node[:,1] = Y.flatten()
print(node)

[[0.         0.        ]
 [0.2        0.        ]
 [0.4        0.        ]
 [0.6        0.        ]
 [0.8        0.        ]
 [1.         0.        ]
 [0.         0.33333333]
 [0.2        0.33333333]
 [0.4        0.33333333]
 [0.6        0.33333333]
 [0.8        0.33333333]
 [1.         0.33333333]
 [0.         0.66666667]
 [0.2        0.66666667]
 [0.4        0.66666667]
 [0.6        0.66666667]
 [0.8        0.66666667]
 [1.         0.66666667]
 [0.         1.        ]
 [0.2        1.        ]
 [0.4        1.        ]
 [0.6        1.        ]
 [0.8        1.        ]
 [1.         1.        ]]


In [14]:
cell = np.zeros((2*NC,3),dtype = np.int)#cell的类型
sign = np.arange(NN).reshape(nx+1,ny+1)#网格每个点的标号，有nx+1列
cell[:NC,0] = sign[0:-1,1:].flatten()#每个小正方形下面的小三角形
cell[:NC,1] = sign[1:,1:].flatten()
cell[:NC,2] = sign[0:-1,0:-1].flatten()
cell[NC:,0] = sign[1:,0:-1].flatten()#每个小正方形上面的小三角形
cell[NC:,1] = sign[0:-1,0:-1].flatten()
cell[NC:,2] = sign[1:,1:].flatten()
print(cell)

[[ 1  5  0]
 [ 2  6  1]
 [ 3  7  2]
 [ 5  9  4]
 [ 6 10  5]
 [ 7 11  6]
 [ 9 13  8]
 [10 14  9]
 [11 15 10]
 [13 17 12]
 [14 18 13]
 [15 19 14]
 [17 21 16]
 [18 22 17]
 [19 23 18]
 [ 4  0  5]
 [ 5  1  6]
 [ 6  2  7]
 [ 8  4  9]
 [ 9  5 10]
 [10  6 11]
 [12  8 13]
 [13  9 14]
 [14 10 15]
 [16 12 17]
 [17 13 18]
 [18 14 19]
 [20 16 21]
 [21 17 22]
 [22 18 23]]


In [ ]:
'''生成mesh,node,cell图表'''
tmesh = TriangleMesh(node, cell)
fig, axes = plt.subplots(1, 3,figsize=(15,15))
tmesh.add_plot(axes[0])
tmesh.find_node(axes[0], showindex=True, markersize=20, fontsize=20)
tmesh.find_cell(axes[0], showindex=True, markersize=15, fontsize=15)
axes[0].set_title('mesh')
for ax in axes.reshape(-1)[1:]:
    ax.axis('tight')
    ax.axis('off')
axes[1].table(cellText=node, rowLabels=np.arange(NN), loc='center')
axes[1].set_title('node', y=0.2)
axes[2].table(cellText=cell, rowLabels=np.arange(2*NC), loc='center')
axes[2].set_title('cell', y=0.9)
plt.tight_layout(pad=0.4, w_pad=1, h_pad=1.0)
plt.show()

In [2]:
x,y=np.mgrid[:4,:6]

In [3]:
print(x,y)

[[0 0 0 0 0 0]
 [1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]] [[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]


In [4]:
x=np.arange(4)
y=np.arange(6)
x,y=np.meshgrid(x,y)

In [5]:
print(x,y)

[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]] [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]]
