In [10]:
import numpy as np
import math
t=np.arange(1000000)
x=[i*0.001 for i in t]
def sin_math(x):
    for i,t in enumerate(x):
        x[i]=math.sin(t)
def sin_numpy(x):
    np.sin(x,x)
def sin_numpy_loop(x):
    for i,t in enumerate(x):
        x[i]=np.sin(t)
x1=x[:]
%time sin_math(x)
x2=np.array(x)
%time sin_numpy(x2)
x3=x[:]
%time sin_numpy_loop(x)

CPU times: user 200 ms, sys: 16 ms, total: 216 ms
Wall time: 218 ms
CPU times: user 15.4 ms, sys: 0 ns, total: 15.4 ms
Wall time: 15.1 ms
CPU times: user 836 ms, sys: 0 ns, total: 836 ms
Wall time: 836 ms


In [3]:
import numpy as np
import math
t=np.arange(1000000)
x=[i*0.001 for i in t]
def sin_math(x):
    for i,t in enumerate(x):
        x[i]=math.sin(t)
def sin_numpy(x):
    np.sin(x,x)
def sin_numpy_loop(x):
    for i,t in enumerate(x):
        x[i]=np.sin(t)
x1=x[:]
%time sin_math(x)
x2=np.array(x)
%time sin_numpy(x2)
x3=x[:]
%time sin_numpy_loop(x)

CPU times: user 213 ms, sys: 4.02 ms, total: 217 ms
Wall time: 217 ms
CPU times: user 15.3 ms, sys: 11 µs, total: 15.3 ms
Wall time: 15 ms
CPU times: user 844 ms, sys: 3.95 ms, total: 847 ms
Wall time: 847 ms


In [4]:
import numpy as np
type(np.sin(0.5))

numpy.float64

In [5]:
type(math.sin(0.5))

float

In [12]:
import numpy as np
a=np.arange(6.0).reshape(2,3)
print(a.item(1,2)),type(a.item(1,2)),type(a[1,2])

5.0


(None, float, numpy.float64)

In [11]:
import numpy as np
a=np.arange(6.0).reshape(2,3)
print(a.item(1,2))

5.0


In [28]:
import numpy as np
a=np.arange(0,4)
b=np.arange(1,5)
np.remainder(a,b)

array([0, 1, 2, 3])

In [34]:
import numpy as np
a=np.arange(0,4)
b=np.arange(1,5)
np.greater(a,b)

array([False, False, False, False])

In [35]:
import numpy as np
a=np.arange(0,4)
b=np.arange(1,5)
np.logical_or(a==b,a>b)

array([False, False, False, False])

In [38]:
import numpy as np
a=np.arange(0,4)
b=np.arange(-1,6,2)
np.any(a==b)

True

In [39]:
import numpy as np
~np.arange(5)

array([-1, -2, -3, -4, -5])

In [16]:
def triangle_wave(x,c,c0,hc):
    x=x-int(x)
    if x>=c:
        r=0.0
    elif x<c0:
        r=x/c0*hc
    else:
        r=(c-x)/(c-c0)*hc
    return r
import numpy as np
x=np.linspace(0,2,100)
y1=np.array([triangle_wave(t,0.6,0.4,1.0)for t in x])
print(y1.dtype)
print(y1)

float64
[0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 0.97979798 0.87878788 0.77777778 0.67676768
 0.57575758 0.47474747 0.37373737 0.27272727 0.17171717 0.07070707
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.02525253 0.07575758 0.12626263 0.17676768
 0.22727273 0.27777778 0.32828283 0.37878788 0.42929293 0.47979798
 0.53030303 0.58080808 0.63131313 0.68181818 0.73232323 0.78282828
 0.83333333 0.88383838 0.93434343 0.98484848 0.92929293 0.82828283
 0.72727273 0.62626263 0.52525253 0.42424242 0.32323232 0.22222222
 0.12121212 0.02020202 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.  

In [1]:
def triangle_wave(x,c,c0,hc):
    x=x-int(x)
    if x>=c:
        r=0.0
    elif x<c0:
        r=x/c0*hc
    else:
        r=(c-x)/(c-c0)*hc
    return r
import numpy as np
x=np.linspace(0,2,100)
triangle_ufunc1=np.frompyfunc(triangle_wave,4,1)
y2=triangle_ufunc1(x,0.6,0.4,1.0)
print(y2.dtype,y2,y2.astype(np.float).dtype)

object [0.0 0.050505050505050504 0.10101010101010101 0.15151515151515152
 0.20202020202020202 0.25252525252525254 0.30303030303030304
 0.3535353535353536 0.40404040404040403 0.45454545454545453
 0.5050505050505051 0.5555555555555556 0.6060606060606061
 0.6565656565656566 0.7070707070707072 0.7575757575757576
 0.8080808080808081 0.8585858585858587 0.9090909090909091
 0.9595959595959597 0.9797979797979797 0.8787878787878788
 0.7777777777777777 0.6767676767676766 0.5757575757575757
 0.4747474747474746 0.3737373737373734 0.2727272727272723
 0.17171717171717119 0.07070707070707062 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.025252525252525415
 0.07575757575757625 0.12626262626262652 0.1767676767676768
 0.22727272727272763 0.2777777777777779 0.32828282828282873
 0.378787878787879 0.4292929292929293 0.4797979797979801
 0.5303030303030304 0.5808080808080812 0.6313131313131315
 0.6818181818181823 0.7323232323232326 0.7828282828282829
 0.8333333333333337 0.

In [3]:
def triangle_wave(x,c,c0,hc):
    x=x-int(x)
    if x>=c:
        r=0.0
    elif x<c0:
        r=x/c0*hc
    else:
        r=(c-x)/(c-c0)*hc
    return r
import numpy as np
x=np.linspace(0,2,100)
triangle_ufunc2=np.vectorize(triangle_wave,otypes=[np.float])
y3=triangle_ufunc2(x,0.6,0.4,1.0)
print(y3.dtype,y3)

float64 [0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 0.97979798 0.87878788 0.77777778 0.67676768
 0.57575758 0.47474747 0.37373737 0.27272727 0.17171717 0.07070707
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.02525253 0.07575758 0.12626263 0.17676768
 0.22727273 0.27777778 0.32828283 0.37878788 0.42929293 0.47979798
 0.53030303 0.58080808 0.63131313 0.68181818 0.73232323 0.78282828
 0.83333333 0.88383838 0.93434343 0.98484848 0.92929293 0.82828283
 0.72727273 0.62626263 0.52525253 0.42424242 0.32323232 0.22222222
 0.12121212 0.02020202 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.  