In [1]:
import numpy as np
n=100000
np.sum(4.0/np.r_[1:n:4,-3:-n:-4])

3.141572653589794

In [7]:
s=0
for i in range(4):
    s+=i
    print("i={}, s={}".format(i, s))
s

i=0, s=0
i=1, s=1
i=2, s=3
i=3, s=6


6

In [16]:
import numpy as np 
a=np.array([1,2,3,4])
b=np.array((5,6,7,8))
c=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
a.shape, b.shape, c.shape
c.shape=4,3
c

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [17]:
import numpy as np
def func2(i,j):
    return(i+1)*(j+1)
np.fromfunction(func2,(9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [1]:
from numpy.lib.stride_tricks import as_strided
import numpy as np
a=np.arange(6)
b=as_strided(a,shape=(4,3),strides=(4,4))
print(b)

[[          0  4294967296           1]
 [ 4294967296           1  8589934592]
 [          1  8589934592           2]
 [ 8589934592           2 12884901888]]


In [2]:
def triangle_wave(x,c,c0,hc):
    x=x-int(x)
    if x>=c:
        r=0.0
    elif x<c0:
        r=x/c0*hc
    else:
        r=(c-x)/(c-c0)*hc
    return r
import numpy as np 
x=np.linspace(0,2,100)
y1=np.array([triangle_wave(t,0.6,0.4,1.0)for t in x])
print(y1.dtype,y1)
triangle_ufunc1=np.frompyfunc(triangle_wave,4,1)
y2=triangle_ufunc1(x,0.6,0.4,1.0)
print(y2.dtype,y2,y2.astype(np.float).dtype)
triangle_ufunc2=np.vectorize(triangle_wave,otypes=[np.float])
y3=triangle_ufunc2(x,0.6,0.4,1.0)
print(y3.dtype,y3)

float64 [0.         0.05050505 0.1010101  0.15151515 0.2020202  0.25252525
 0.3030303  0.35353535 0.4040404  0.45454545 0.50505051 0.55555556
 0.60606061 0.65656566 0.70707071 0.75757576 0.80808081 0.85858586
 0.90909091 0.95959596 0.97979798 0.87878788 0.77777778 0.67676768
 0.57575758 0.47474747 0.37373737 0.27272727 0.17171717 0.07070707
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.02525253 0.07575758 0.12626263 0.17676768
 0.22727273 0.27777778 0.32828283 0.37878788 0.42929293 0.47979798
 0.53030303 0.58080808 0.63131313 0.68181818 0.73232323 0.78282828
 0.83333333 0.88383838 0.93434343 0.98484848 0.92929293 0.82828283
 0.72727273 0.62626263 0.52525253 0.42424242 0.32323232 0.22222222
 0.12121212 0.02020202 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.  